<!DOCTYPE productos [
    <!ELEMENT productos (producto+)>
    <!ELEMENT producto (nombre, identificacion, id)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT identificacion (#PCDATA)>
    <!ELEMENT codigo (#PCDATA)>
    <!ELEMENT id (#PCDATA)>
]>
<productos>
  <producto>
    <nombre>martillo</nombre>
    <identificacion>
        Quedan 14 unidades.
        <codigo>MAR264</codigo>
    </identificacion>
    <id>678984</id>
  </producto>
  <producto>
    <nombre>destornillador</nombre>
    <identificacion>
        Quedan 6 unidades.
        <codigo>Mrh26L</codigo>
    </identificacion>
    <id>678984</id>
  </producto>
</productos>
