=== Ruben0508/tareagit/xml/2/dtd.dtd
<!ELEMENT biblioteca (libro*, revista*, pelicula*)>
<!ELEMENT libro (titulo, autor, anio_publicacion, genero_literario, numero_paginas)>
<!ELEMENT revista (titulo, editorial, anio_publicacion, numero_volumen)>
<!ELEMENT pelicula (titulo, director, anio_estreno, genero_cinematografico, duracion_minutos)>

<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT anio_publicacion (#PCDATA)>
<!ELEMENT genero_literario (#PCDATA)>
<!ELEMENT numero_paginas (#PCDATA)>
<!ELEMENT editorial (#PCDATA)>
<!ELEMENT numero_volumen (#PCDATA)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT anio_estreno (#PCDATA)>
<!ELEMENT genero_cinematografico (#PCDATA)>
<!ELEMENT duracion_minutos (#PCDATA)>

=== Ruben0508/tareagit/xml/2/2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "dtd.dtd">
<biblioteca>
    <libro>
        <titulo>Cien años de soledad</titulo>
        <autor>Gabriel García Márquez</autor>
        <anio_publicacion>1967</anio_publicacion>
        <genero_literario>Realismo mágico</genero_literario>
        <numero_paginas>432</numero_paginas>
    </libro>
    
    <revista>
        <titulo>National Geographic</titulo>
        <editorial>National Geographic Society</editorial>
        <anio_publicacion>2022</anio_publicacion>
        <numero_volumen>240</numero_volumen>
    </revista>
    
    <pelicula>
        <titulo>El Padrino</titulo>
        <director>Francis Ford Coppola</director>
        <anio_estreno>1972</anio_estreno>
        <genero_cinematografico>Drama</genero_cinematografico>
        <duracion_minutos>175</duracion_minutos>
    </pelicula>
</biblioteca>
